### ISSUE TITLE
[Problem] Syntax error in ./src/index.js

### ISSUE THREAD

**Issue by njs03332** [JW275/SWPP2018_01_Group15_FrontEnd#9]
![image](https://user-images.githubusercontent.com/37107740/39957266-2cfe0f82-562b-11e8-8d51-b44b2cb4f88d.png)

**Comment by ilil96** [comment]
`{
  "presets": [
    ["env", {
      "modules": false
    }],
    "react",
    "stage-1"
  ],
  "plugins": [
    "react-hot-loader/babel"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    },
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    },
    "production": {
      "plugins": [
        "transform-react-remove-prop-types"
      ]
    }
  }
}`

.babelrc
